# Generated by Django 6.0.5 on 2026-06-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student_quantity_alter_student_admission_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=30)),
                ('component_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.CharField(max_length=100)),
                ('reason', models.CharField(default='Deleted by Admin', max_length=200)),
            ],
            options={
                'db_table': 'maintenance_history',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=20),
        ),
    ]
