# Generated by Django 6.0.5 on 2026-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_maintenancehistory_student_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
